server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:13307/toy-board?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 4        # 최소 유휴 커넥션 수
      maximum-pool-size: 4   # 최대 커넥션 수
      idle-timeout: 10000    # 유휴 커넥션 유지 시간 (ms)
      max-lifetime: 30000    # 커넥션 최대 생존 시간 (ms)
      connection-timeout: 180000 # 커넥션 가져오기 최대 대기 시간 (ms)

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # 개발 환경용
    generate-ddl: true
    show-sql: true
    open-in-view: false

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET}